name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push Docker Image

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Build
      run: docker build -t ${{ secrets.DOCKER_USER }}/edge-api:latest .

    - name: Upload container to Docker Hub with Push
      run: docker push ${{ secrets.DOCKER_USER }}/edge-bastion-api:latest

    - name: Logout from Docker Hub
      run: docker logout
